Django/house/urls.py
from django.urls import path
from . import views
# Create your tests here.
app_name = 'house'

urlpatterns = [
    path('solution', views.solution, name='solution'),
    path('detail', views.detail, name='detail'),

]

Django/last_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name='home.html'),name='home'),
    path('admin/', admin.site.urls),
    path('house/', include('house.urls')),
]

Django/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{%endblock title%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-food.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <style>
        body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif, 'Noto Sans KR', sans-serif}
        .myLink {display: none}

        header {
        margin-bottom: 30px;
        }


        #mapwrap{position:relative;overflow:hidden;}
        .category, .category *{margin:0;padding:0;color:#000;}   
        .category {position:absolute;overflow:hidden;top:10px;left:10px;width:200px;height:60px;z-index:10;border:1px solid black;font-family:'Malgun Gothic','맑은 고딕',sans-serif;font-size:12px;text-align:center;background-color:#fff;}
        .category .menu_selected {background:#0b0985;color:#fff;border-left:1px solid #915B2F;border-right:1px solid #915B2F;margin:0 -1px;height:60px;} 
        .category li{list-style:none;float:left;width:50px;height:45px;padding-top:5px;cursor:pointer;} 
        .category .ico_comm {display:block;margin:0 auto 2px;width:22px;height:26px;background:url('https://postfiles.pstatic.net/MjAyMDEwMjdfMjIy/MDAxNjAzNzk0NjYwNTYw.tqcDYPban602gIpHpuMcE0vaYjGCk6HPdMgeR6G1oo0g.3kjOuqzzqTWCMqmPO7ki_eLCVRNu_m5DPdz0FdU3Olwg.PNG.snrnrp2004/category_(1)_(1).png?type=w773') no-repeat;} 
        .category .ico_house {background-position:-10px 0;}  
        .category .ico_store {background-position:-10px -36px;}   
    </style>

    <script type="text/javascript">
        function ConditionCheck() {
            var table = $('input[name="table"]:checked').val();
            var input_rent = $('input[name="input_rent"]:checked').val();
            var q1 = $('#q1').val();
            //var q2 = $('#q2').val();
            var q3 = $('#q3').val();
            var con_input = [];
                $('input[name="con_input"]:checked').each(function(i){
                    con_input.push($(this).val());
                });
            if(!table || !input_rent || !q1 || !q3 || !con_input) {
                alert('조건을 모두 입력해주세요.');
            }else {
                searchForm.submit();
            }
        }
    </script>

</head>
<body class="w3-light-grey">
  <div class="w3-bar w3-border-bottom w3-xlarge" style="background-color:#80ced6;"><font size="4"><b>
    <!--로그인한 사용자 :로그아웃, 제품목록 / 로그아웃한 사용자 : 가입, 로그인 / 공통 : 제품목록-->
    <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-text-light grey w3-hover-dark-grey"> HOME </a>
    <a href='/admin' class="w3-bar-item w3-button w3-text-light grey w3-hover-dark-grey"> ADMIN </a>
  </b>
  </div>

  <header class="w3-display-container w3-content w3-hide-small" style="max-width:1500px;">
    <img src="https://lh3.googleusercontent.com/NQlHJAG2womFkaNs3HmfxPd7vMgHqJO6nBFxBFzglmgwMGwlHhxoAiJGCo8w-7NyriHGICbXys0oplzV8WsJUoD2gP6ozR-Mui64j4r1pR7D3w35i2ybh9xoWfnuVklgnC_GTO_UVdjqn-SY059Fy9JpYPlzw7vQnxIxxolxtAIoJX4vwrsVv3m_bW252hq8ssbLeOsYNCcyfHfE02fWGwqwDZ96oXKhx1bf-3Vc3CkXB2gugvumfgVjMzWG3ZTUI4E9rEWNhH5BOr7KKo1PYfI4aTCs8uasF0fN-EAe_gmvDWz6l0Ry2raqXnv5hfwh8V34cAs8e29eBFgG6ancNbIJkKqIvoA9SzYo2QqooOZIO3KL3mU8tiZJTrNx3LlUSHNxyRB9r1WSRDhbLEPc7jUVXVY5-zA8OYXGwX14XmhjT00o56BYrECVTqcHMRV1aXiaedfv9P_7_iAV7CEajQ34z6JR1-nblGZdUhq_vdymwlYBIkQu1l12cFEX3olsvrSoGusUUKJKQi3NARbzPzP2-MQIcSrvIpZ46Bc6Iia-GqAjJHl--e3Z-thWMbet1rO6LHRJyV054_4iDssfWnNfQSqCu-jnSccihQD9IWUUbhBrlbWX3QAItLWC3Gn12qseGbHjGZ13o-EaERYtQKaqeGo-Mpcz1OMZGpJHD736NstTAVh-nRY0jn-r=w1500-h450-no?authuser=0" width="1500" height="450">
    <div class="w3-display-middle" style="width:65%">
  </header>

  <div class="w3-content" style="max-width:1500px;">
{% block content %}
{% endblock content %}
</div>
</body>
<footer class="w3-container w3-center w3-opacity w3-margin-bottom">
  <div class="w3-xlarge w3-padding-64">
    <h5>Find Us On</h5>
    <i class='fab fa-github' style='font-size:36px'></i>
  </div>
</footer>
</html>

Django/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="w3-content w3-margin-top" style="width:900px; font-family:Noto Sans KR">

    <form name="searchForm" action="{% url 'house:solution' %}" method='GET'>
        {% csrf_token %}
        <br>
        <div class="row">
            <div class="col">
                <h5><b>부동산 유형</b></h5>
                <div class="form-check", style="font-size:17px">
                    <label class="form-check-label">
                    <input type="radio"  name="table" class="form-check-input" value="officetels">오피스텔</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <label class="form-check-label">
                    <input type="radio"  name="table" class="form-check-input" value="villa">빌라</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <label class="form-check-label">
                    <input type="radio"  name="table" class="form-check-input" value="one_two_room">단독다가구</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </div>
            </div>
            <div class="col">
                <h5><b>전/월세</b></h5>
                <div class="form-check", style="font-size:17px">
                    <label class="form-check-label">
                    <input type="radio"  name="input_rent" class="form-check-input" value="전세" onclick='a()'>전세</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="radio"  name="input_rent" class="form-check-input" value="월세" onclick='b()'>월세</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </div>
            </div>
        </div>
        <br>
        <br>
        <div class="row">
            <div class="col">
                <h5><b>보증금</h5></b>
                <p>
                <input type='search' id="q1" class="form-control" placeholder="만원 단위로 입력하세요(1000만원인 경우 1000)" name='q1' value='{{ q1 }}'>
            </div>
            <div class="col">
                <div id="rent" style='display:none'>
                <h5><b>월세</h5></b>
                <input type='search' id="q2" class="form-control" placeholder="만원 단위로 입력하세요(40만원인 경우 40)" name='q2' value='{{ q2 }}'>
                </div>
            </div>
        </div>
        <br>
        <h5><b>직장주소</h5></b>
        <input type='search' id='q3' class="form-control" placeholder="(ex. 서울특별시 서초구 효령로)" name='q3' value='{{ q3 }}' style="max-width:1000px">
        <br>
        <p>
        <div class="row">
            <div class="col" style="max-width:105px;">
                <h5><b>편의시설</b></h5>
            </div>
            <div class="cell" style="font-size:15px">
                3개까지 선택
            </div>
        </div>
            <div class="form-check" style="font-size:17px">
                <div class="row">
                    <div class="col" style="max-width:110px;">
                    <input onclick="CountChecked(this)" type="checkbox" class="form-check-input"  name="con_input" value="병원">
                    병원
                    </div>
                    <div class="col" style="max-width:110px;">
                    <input onclick="CountChecked(this)" type="checkbox" class="form-check-input"  name="con_input" value="마트">
                    마트
                    </div>
                    <div class="col" style="max-width:150px;">
                    <input onclick="CountChecked(this)" type="checkbox" class="form-check-input"  name="con_input" value="패스트푸드">
                    패스트푸드
                    </div>
                    <div class="col" style="max-width:110px;">
                    <input onclick="CountChecked(this)" type="checkbox" class="form-check-input"  name="con_input" value="카페">
                    카페
                    </div>
                </div>
            </div>
            <div class="form-check" style="font-size:17px">
                <div class="row">
                    <div class="col" style="max-width:110px;">
                        <input onclick="CountChecked(this)" type="checkbox" class="form-check-input"  name="con_input" value="문화시설">
                        문화시설
                    </div>
                    <div class="col" style="max-width:110px;">
                        <input onclick="CountChecked(this)" type="checkbox" class="form-check-input"  name="con_input" value="편의점">
                        편의점
                    </div>
                    <div class="col" style="max-width:150px;">
                        <input onclick="CountChecked(this)" type="checkbox" class="form-check-input"  name="con_input" value="세탁소">
                        세탁소
                    </div>
                    <div class="col" style="max-width:110px;">
                        <input onclick="CountChecked(this)" type="checkbox" class="form-check-input"  name="con_input" value="다이소">
                        다이소
                    </div>
                    <div class="col" style="max-width:160px;"
                        <input onclick="CountChecked(this)" type="checkbox" class="form-check-input"  name="con_input" value="실내운동시설">
                        실내운동시설
                    </div>
                </div>
            </div>
            <br>
            <br>
            <button type="submit" class="btn btn-secondary btn-lg " onclick="ConditionCheck()"><i class="fa fa-search"></i>  검색</button> 
    </form>
</div>

<script>
    function a(){
        document.getElementById('rent').style.display='none';
    }
    function b(){
        document.getElementById('rent').style.display='block';
    }
</script>

<script type="text/javascript">
    var maxCount = 3;								// 카운트 최대값은 2
    var count = 0;   								// 카운트, 0으로 초기화 설정
    function CountChecked(field){ 					// field객체를 인자로 하는 CountChecked 함수 정의
        if (field.checked) {						// 만약 field의 속성이 checked 라면(사용자가 클릭해서 체크상태가 된다면)
            count += 1;								// count 1 증가
        }
        else {										// 아니라면 (field의 속성이 checked가 아니라면)
            count -= 1;								// count 1 감소
        }
        if (count > maxCount) {						// 만약 count 값이 maxCount 값보다 큰 경우라면
            field.checked = false;						// (마지막 onclick한)field 객체의 checked를 false(checked가 아닌 상태)로 만든다.
            count -= 1;									// 이때 올라갔던 카운트를 취소처리해야 하므로 count를 1 감소시킨다.
        }
    }
</script>
{% endblock content %}